spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://localhost:5432/taskapp
spring.datasource.username=mayhrem
spring.datasource.password=TaSkApP-1920892

spring.datasource.driver-class-name=org.postgresql.Driver