apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: mayhrem-task-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
      - name: analytics-service
        image: mayhrem/analytics-service:1.0.0
        ports:
        - containerPort: 8080
      imagePullSecrets: 
      - name: task-key
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: mayhrem-task-app
spec:
  selector:
    app: analytics-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30079
  type: NodePort