apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"name":"mayhrem-task-app"}}
  creationTimestamp: "2025-01-13T01:25:36Z"
  labels:
    kubernetes.io/metadata.name: mayhrem-task-app
  name: mayhrem-task-app
  resourceVersion: "28574"
  uid: 3fae80ec-ee9b-43f4-9e76-643a005973b6
spec:
  finalizers:
  - kubernetes
status:
  phase: Active