apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  namespace: mayhrem-task-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
      - name: task-service
        image: mayhrem/task-service:3.0.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  selector:
    app: task-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30085
  type: NodePort