version: '3.8'

services:
  auth-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskapp
      SPRING_DATASOURCE_USERNAME: mayhrem
      SPRING_DATASOURCE_PASSWORD: TaSkApP-1920892
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: taskapp
      POSTGRES_USER: mayhrem
      POSTGRES_PASSWORD: TaSkApP-1920892
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: